#!/usr/bin/env python3
# Copyright 2026 Sebastian Werner
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Generates the Rust Adobe CMYK lookup table from the retained C++ oracle."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "core/fxge/dib/cfx_cmyk_to_srgb.cpp"
OUTPUT = ROOT / "core/fxge/dib/rust/pdfium_rust_cmyk_table.rs"
ENTRY_PATTERN = re.compile(r"\{(\d+),\s*(\d+),\s*(\d+)\}")


def render() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    table_start = source.index("constexpr std::array<const FX_RGB_STRUCT<uint8_t>")
    table_end = source.index("}};", table_start)
    entries = ENTRY_PATTERN.findall(source[table_start:table_end])
    if len(entries) != 9**4:
        raise ValueError(f"expected 6561 CMYK entries, found {len(entries)}")

    lines = [
        "// Copyright 2026 Sebastian Werner",
        "// Use of this source code is governed by a BSD-style license that can be",
        "// found in the LICENSE file.",
        "//",
        "// @generated by testing/tools/generate_rust_cmyk_table.py",
        "// Source: core/fxge/dib/cfx_cmyk_to_srgb.cpp",
        "",
        "pub(crate) static CMYK: [[u8; 3]; 9 * 9 * 9 * 9] = [",
    ]
    lines.extend(f"    [{red}, {green}, {blue}]," for red, green, blue in entries)
    lines.append("];\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        return 0 if OUTPUT.read_text(encoding="utf-8") == generated else 1
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
